theme = "dracula"

[editor]
true-color = true
color-modes = true
line-number = "relative"
cursorline = true
auto-completion = false
auto-format = false
auto-pairs = false

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
C-space = ["completion"]
