theme = "dracula"

[editor]
true-color = true
color-modes = true
line-number = "relative"
cursorline = true
auto-completion = false
auto-format = false

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
#X = ["extend_line_above"]

[keys.insert]
C-space = ["completion"]
